version: "3.0"
services:
  redis:
    container_name: vertx_test_redis
    image: redis
    ports:
      - "6379:6379"
  mysql:
    container_name: vertx_test_mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
